# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-29 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0002_book_pic_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
